---
- hosts: localhost
  connection: local
  become: true
  vars:
  tasks:
    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing dumb-init
      apt:
        deb: "https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb"

    - name: Installing Snort Pre-Reqs
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - 'build-essential'
        - 'ethtool'
        - 'flex'
        - 'iproute'
        - 'libpcap-dev'
        - 'libpcre3-dev'
        - 'libdumbnet-dev'
        - 'zlib1g-dev'

    - name: Installing Snort
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'oinkmaster'
        - 'snort'
